import * as yup from "yup";
import { VALIDATION_CONFIG, VALIDATION_MESSAGES } from "../constants/validation.constants";

export const identificationSchema = yup
  .string()
  .required(VALIDATION_MESSAGES.IDENTIFICATION.REQUIRED)
  .matches(/^\d+$/, VALIDATION_MESSAGES.IDENTIFICATION.NUMERIC)
  .min(VALIDATION_CONFIG.IDENTIFICATION.MIN_LENGTH, VALIDATION_MESSAGES.IDENTIFICATION.MIN_LENGTH)
  .max(VALIDATION_CONFIG.IDENTIFICATION.MAX_LENGTH, VALIDATION_MESSAGES.IDENTIFICATION.MAX_LENGTH);

export const passwordSchema = yup
  .string()
  .required(VALIDATION_MESSAGES.PASSWORD.REQUIRED)
  .min(VALIDATION_CONFIG.PASSWORD.MIN_LENGTH, VALIDATION_MESSAGES.PASSWORD.MIN_LENGTH);

export const passwordStrongSchema = yup
  .string()
  .required(VALIDATION_MESSAGES.PASSWORD.REQUIRED)
  .min(VALIDATION_CONFIG.PASSWORD.MIN_LENGTH, VALIDATION_MESSAGES.PASSWORD.MIN_LENGTH)
  .matches(/[A-Z]/, VALIDATION_MESSAGES.PASSWORD.UPPERCASE)
  .matches(/[a-z]/, VALIDATION_MESSAGES.PASSWORD.LOWERCASE)
  .matches(/[0-9]/, VALIDATION_MESSAGES.PASSWORD.NUMBER);

export const confirmPasswordSchema = yup
  .string()
  .required(VALIDATION_MESSAGES.CONFIRM_PASSWORD.REQUIRED)
  .oneOf([yup.ref("password")], VALIDATION_MESSAGES.CONFIRM_PASSWORD.MATCH);

export const nameSchema = yup
  .string()
  .required(VALIDATION_MESSAGES.NAME.REQUIRED)
  .min(VALIDATION_CONFIG.NAME.MIN_LENGTH, VALIDATION_MESSAGES.NAME.MIN_LENGTH)
  .max(VALIDATION_CONFIG.NAME.MAX_LENGTH, VALIDATION_MESSAGES.NAME.MAX_LENGTH);

export const citySchema = yup
  .string()
  .required(VALIDATION_MESSAGES.CITY.REQUIRED)
  .min(VALIDATION_CONFIG.CITY.MIN_LENGTH, VALIDATION_MESSAGES.CITY.MIN_LENGTH);

export const monthlyIncomeSchema = yup
  .number()
  .typeError(VALIDATION_MESSAGES.MONTHLY_INCOME.REQUIRED)
  .required(VALIDATION_MESSAGES.MONTHLY_INCOME.REQUIRED)
  .min(1, VALIDATION_MESSAGES.MONTHLY_INCOME.MIN);

export const dataTreatmentSchema = yup
  .boolean()
  .oneOf([true], VALIDATION_MESSAGES.DATA_TREATMENT.REQUIRED)
  .required(VALIDATION_MESSAGES.DATA_TREATMENT.REQUIRED);
